"use client";
import {useState} from "react"; import {createClient} from "@/lib/supabase/browser"; import {Plus,Trash2,Save} from "lucide-react";
type Opt={id?:string,label:string,is_correct:boolean,position:number}; type Q={id?:string,prompt:string,position:number,assessment_options:Opt[]};
export function AssessmentBuilder({courseId,initial}:{courseId:string,initial:any|null}){const s=createClient();const [assessment,setAssessment]=useState(initial??{title:'Avaliação final',instructions:'Responda às questões e alcance a nota mínima para aprovação.',passing_score:70,max_attempts:3,is_published:false});const [qs,setQs]=useState<Q[]>(initial?.assessment_questions??[]);const [msg,setMsg]=useState('');
 const save=async()=>{setMsg('Salvando...');let id=assessment.id;const payload={course_id:courseId,title:assessment.title,instructions:assessment.instructions,passing_score:+assessment.passing_score,max_attempts:+assessment.max_attempts,is_published:!!assessment.is_published};if(id){const {error}=await s.from('course_assessments').update(payload).eq('id',id);if(error)return setMsg(error.message)}else{const {data,error}=await s.from('course_assessments').insert(payload).select().single();if(error)return setMsg(error.message);id=data.id;setAssessment({...assessment,id})}
 for(let i=0;i<qs.length;i++){let q=qs[i],qid=q.id;if(qid){await s.from('assessment_questions').update({prompt:q.prompt,position:i+1}).eq('id',qid)}else{const {data}=await s.from('assessment_questions').insert({assessment_id:id,prompt:q.prompt,position:i+1}).select().single();qid=data?.id;q.id=qid}for(let j=0;j<q.assessment_options.length;j++){const o=q.assessment_options[j];const op={question_id:qid,label:o.label,is_correct:o.is_correct,position:j+1};if(o.id)await s.from('assessment_options').update(op).eq('id',o.id);else{const {data}=await s.from('assessment_options').insert(op).select().single();o.id=data?.id}}}setQs([...qs]);setMsg('Avaliação salva.');};
 const addQ=()=>setQs([...qs,{prompt:'',position:qs.length+1,assessment_options:[{label:'',is_correct:true,position:1},{label:'',is_correct:false,position:2}]}]);
 const removeQ=async(i:number)=>{const q=qs[i];if(q.id)await s.from('assessment_questions').delete().eq('id',q.id);setQs(qs.filter((_,x)=>x!==i))};
 return <section className="admin-panel assessment-builder"><div className="panel-title"><div><h2>Avaliação e aprovação</h2><p>Configure a prova final, nota mínima e número de tentativas.</p></div><button className="btn btn-primary" onClick={save}><Save size={16}/> Salvar avaliação</button></div><div className="assessment-settings"><label>Título<input className="field" value={assessment.title} onChange={e=>setAssessment({...assessment,title:e.target.value})}/></label><label>Nota mínima (%)<input className="field" type="number" min="0" max="100" value={assessment.passing_score} onChange={e=>setAssessment({...assessment,passing_score:e.target.value})}/></label><label>Tentativas<input className="field" type="number" min="1" value={assessment.max_attempts} onChange={e=>setAssessment({...assessment,max_attempts:e.target.value})}/></label><label className="assessment-publish"><input type="checkbox" checked={assessment.is_published} onChange={e=>setAssessment({...assessment,is_published:e.target.checked})}/> Publicada para os alunos</label><label className="assessment-instructions">Instruções<textarea className="field" value={assessment.instructions??''} onChange={e=>setAssessment({...assessment,instructions:e.target.value})}/></label></div>{qs.map((q,i)=><div className="question-editor" key={q.id??i}><div className="question-head"><b>Questão {i+1}</b><button onClick={()=>removeQ(i)}><Trash2 size={16}/></button></div><input className="field" placeholder="Digite a pergunta" value={q.prompt} onChange={e=>{q.prompt=e.target.value;setQs([...qs])}}/><div className="option-list">{q.assessment_options.map((o,j)=><div className="option-row" key={o.id??j}><input type="radio" name={`correct-${i}`} checked={o.is_correct} onChange={()=>{q.assessment_options.forEach(x=>x.is_correct=false);o.is_correct=true;setQs([...qs])}}/><input className="field" placeholder={`Alternativa ${j+1}`} value={o.label} onChange={e=>{o.label=e.target.value;setQs([...qs])}}/><button onClick={async()=>{if(o.id)await s.from('assessment_options').delete().eq('id',o.id);q.assessment_options.splice(j,1);setQs([...qs])}}><Trash2 size={15}/></button></div>)}</div><button className="text-action" onClick={()=>{q.assessment_options.push({label:'',is_correct:false,position:q.assessment_options.length+1});setQs([...qs])}}><Plus size={15}/> Alternativa</button></div>)}<button className="btn btn-secondary add-question" onClick={addQ}><Plus size={17}/> Adicionar questão</button>{msg&&<p className="builder-message">{msg}</p>}</section>}
