"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/browser";
import { BookOpen, ChevronDown, ChevronUp, Eye, FileText, GripVertical, Link2, Pencil, Plus, Trash2, Video } from "lucide-react";

type Lesson={id:string;title:string;description?:string|null;position:number;duration_minutes?:number|null;is_preview:boolean;content_type:string;video_url?:string|null;body?:string|null;material_url?:string|null};
type Module={id:string;title:string;description?:string|null;position:number;course_lessons:Lesson[]};
export function CourseBuilder({courseId,initialModules}:{courseId:string;initialModules:Module[]}){
 const router=useRouter(); const supabase=useMemo(()=>createClient(),[]); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [open,setOpen]=useState<string|null>(null);
 async function addModule(){const title=prompt("Nome do novo módulo:");if(!title)return;setBusy(true);const pos=(initialModules.at(-1)?.position||0)+1;const {error}=await supabase.from('course_modules').insert({course_id:courseId,title,position:pos});setBusy(false);if(error)setError(error.message);else router.refresh()}
 async function addLesson(moduleId:string,position:number){const title=prompt("Título da nova aula:");if(!title)return;setBusy(true);const {error}=await supabase.from('course_lessons').insert({module_id:moduleId,title,position,content_type:'video'});setBusy(false);if(error)setError(error.message);else router.refresh()}
 async function remove(table:'course_modules'|'course_lessons',id:string,label:string){if(!confirm(`Excluir ${label}? Esta ação não poderá ser desfeita.`))return;setBusy(true);const {error}=await supabase.from(table).delete().eq('id',id);setBusy(false);if(error)setError(error.message);else router.refresh()}
 async function moveModule(m:Module,delta:number){const other=initialModules.find(x=>x.position===m.position+delta);if(!other)return;setBusy(true);await supabase.from('course_modules').update({position:other.position}).eq('id',m.id);await supabase.from('course_modules').update({position:m.position}).eq('id',other.id);setBusy(false);router.refresh()}
 return <section className="admin-panel academy-builder"><div className="panel-title"><div><h2>Editor do curso</h2><p>Crie módulos, aulas e materiais e organize a ordem de aprendizagem.</p></div><button className="btn btn-primary" onClick={addModule} disabled={busy}><Plus size={17}/> Novo módulo</button></div>{error&&<p className="builder-error">{error}</p>}
 {initialModules.map((m,idx)=><div className="builder-module" key={m.id}><div className="builder-module-head"><div className="builder-order"><GripVertical size={18}/><b>{m.position}. {m.title}</b><span>{m.course_lessons?.length||0} aulas</span></div><div className="builder-actions"><button title="Subir" disabled={idx===0||busy} onClick={()=>moveModule(m,-1)}><ChevronUp size={17}/></button><button title="Descer" disabled={idx===initialModules.length-1||busy} onClick={()=>moveModule(m,1)}><ChevronDown size={17}/></button><button title="Excluir módulo" onClick={()=>remove('course_modules',m.id,'este módulo e suas aulas')}><Trash2 size={17}/></button></div></div>
 {(m.course_lessons||[]).sort((a,b)=>a.position-b.position).map(l=><div className="builder-lesson" key={l.id}><div className="lesson-type">{l.content_type==='video'?<Video size={17}/>:l.content_type==='pdf'?<FileText size={17}/>:l.content_type==='link'?<Link2 size={17}/>:<BookOpen size={17}/>}</div><div className="lesson-info"><b>{l.position}. {l.title}</b><small>{l.duration_minutes?`${l.duration_minutes} min · `:''}{l.content_type}{l.is_preview?' · Prévia pública':''}</small></div><button className="lesson-edit" onClick={()=>setOpen(open===l.id?null:l.id)}><Pencil size={16}/> Editar</button><button className="lesson-delete" onClick={()=>remove('course_lessons',l.id,'esta aula')}><Trash2 size={16}/></button>{open===l.id&&<LessonEditor lesson={l} onDone={()=>{setOpen(null);router.refresh()}}/>}</div>)}
 <button className="add-lesson" disabled={busy} onClick={()=>addLesson(m.id,(m.course_lessons?.length||0)+1)}><Plus size={16}/> Adicionar aula</button></div>)}
 {!initialModules.length&&<div className="member-empty"><h3>Comece criando o primeiro módulo</h3><p>Depois você poderá adicionar aulas em vídeo, texto, PDF ou link e acompanhar a conclusão dos membros.</p><button className="btn btn-primary" onClick={addModule}><Plus size={17}/> Criar primeiro módulo</button></div>}</section>
}
function LessonEditor({lesson,onDone}:{lesson:Lesson;onDone:()=>void}){const supabase=useMemo(()=>createClient(),[]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const payload={title:String(f.get('title')||''),description:String(f.get('description')||'')||null,content_type:String(f.get('content_type')||'video'),video_url:String(f.get('video_url')||'')||null,body:String(f.get('body')||'')||null,material_url:String(f.get('material_url')||'')||null,duration_minutes:Number(f.get('duration_minutes')||0)||null,is_preview:f.get('is_preview')==='on'};const {error}=await supabase.from('course_lessons').update(payload).eq('id',lesson.id);setBusy(false);if(error)setError(error.message);else onDone()}
return <form className="lesson-editor" onSubmit={save}><div className="form-two-wide"><label>Título<input className="field" name="title" defaultValue={lesson.title} required/></label><label>Tipo<select className="field" name="content_type" defaultValue={lesson.content_type}><option value="video">Vídeo</option><option value="text">Texto</option><option value="pdf">PDF</option><option value="link">Link</option></select></label></div><label>Descrição<input className="field" name="description" defaultValue={lesson.description||''}/></label><div className="form-two-wide"><label>URL do vídeo<input className="field" name="video_url" defaultValue={lesson.video_url||''} placeholder="YouTube, Vimeo..."/></label><label>Duração (min)<input className="field" type="number" min="0" name="duration_minutes" defaultValue={lesson.duration_minutes||''}/></label></div><label>Conteúdo em texto<textarea className="field course-textarea" name="body" defaultValue={lesson.body||''}/></label><label>Material / PDF / link complementar<input className="field" name="material_url" defaultValue={lesson.material_url||''}/></label><label className="consent"><input type="checkbox" name="is_preview" defaultChecked={lesson.is_preview}/> Permitir prévia desta aula</label>{error&&<p className="form-error">{error}</p>}<div className="editor-buttons"><button type="button" className="btn btn-secondary" onClick={onDone}>Cancelar</button><button className="btn btn-primary" disabled={busy}>{busy?'Salvando...':'Salvar aula'}</button></div></form>}
